# Generated by Django 4.0.6 on 2022-07-30 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_shopifyapps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopifyapps',
            name='reviews_rating',
            field=models.FloatField(default=0.0),
        ),
    ]
