# Generated by Django 4.0.6 on 2022-07-30 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_alter_shopifyapps_reviews_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppDelta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_rank', models.FloatField()),
                ('new_rank', models.FloatField()),
                ('app_previous_details', models.JSONField(default=dict)),
                ('app_new_details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('app_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.shopifyapps')),
            ],
        ),
    ]
