# Generated by Django 4.0.6 on 2022-07-31 05:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_appdelta'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopifyapps',
            name='created_at',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
