# Generated by Django 4.0.6 on 2022-07-31 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0005_shopifyapps_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopifyapps',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='shopifyapps',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
