# Generated by Django 4.0.6 on 2022-07-31 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0006_alter_shopifyapps_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopifyapps',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
