# Generated by Django 4.0.6 on 2022-07-31 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0007_alter_shopifyapps_created_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shopifyapps',
            unique_together={('name', 'developed_by', 'created_at')},
        ),
    ]
