# Generated by Django 4.0.6 on 2022-07-31 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0009_appdelta_rank_delta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appdelta',
            old_name='app_name',
            new_name='app',
        ),
    ]
